name: build and push client-node docker image to ghcr.io

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v4
      run: docker image ls
    # build_and_push_image:
    #   runs-on: ubuntu-latest
    #   # `GITHUB_TOKEN` permissions for the actions in this job
    #   permissions:
    #     contents: read
    #     packages: write

    #   steps:
    #       uses: actions/checkout@v4

    #     - name: log in to the container registry
    #       uses: docker/login-action@v3
    #       with:
    #         registry: ${{ env.REGISTRY }}
    #         username: ${{ github.actor }}
    #         password: ${{ secrets.GITHUB_TOKEN }}

    #     - name: extract metadata (tags, labels) for docker
    #       id: meta
    #       uses: docker/metadata-action@v5
    #       with:
    #         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    #     - name: build and push docker image
    #       uses: docker/build-push-action@v5
    #       with:
    #         context: .
    #         dockerfile: client-node-comfyui.dockerfile
    #         push: true
    #         tags: ${{ steps.meta.outputs.tags }}
    #         labels: ${{ steps.meta.outputs.labels }}
